### ISSUE TITLE
おすすめ商品登録した商品を削除すると、商品の無いレコードが表示される

### ISSUE THREAD

**Issue by ryo-endo** [eccubevn/Recommend-plugin#3]
おすすめ商品登録した商品を削除すると、商品の無いレコードが表示されます。
## 手順
1. 商品Aをおすすめ商品として登録。
2. 商品Aを削除。
3. おすすめ商品一覧を確認
   　→ 商品の無いレコードが表示されている（NG）

![image](https://cloud.githubusercontent.com/assets/16891862/19432030/b17f67d2-9495-11e6-8a34-c3a3f0f4c2bf.png)
## 期待結果

削除した商品のレコードは表示しないこと。

**Comment by ryo-endo** [comment]
SQLiteで発生しています。

**Comment by lqdung-lockon** [comment]
I can't reproduce. Can you give me more condition for this error case?

**Comment by ryo-endo** [comment]
@lqdung-lockon 
3.0.10, pgsqlでも発生確認しました。

**Comment by ryo-endo** [comment]
発生手順：
おすすめ商品に登録している商品を削除するだけです。

**Comment by lqdung-lockon** [comment]
I fixed. Please check!.
