### ISSUE TITLE
おすすめ商品登録ページのレイアウト改善要望

### ISSUE THREAD

**Issue by ryo-endo** [eccubevn/Recommend-plugin#4]
赤枠で囲った部分のレイアウトが格好悪いので、
もう少し他のページと統一したようなレイアウトにして欲しいです。

![image](https://cloud.githubusercontent.com/assets/16891862/19432164/44f01250-9496-11e6-8ccb-f8fb573d4353.png)

**Comment by lqdung-lockon** [comment]
I've fixed it. Please check!
