### ISSUE TITLE
おすすめ商品一覧のスタイルを、EC-CUBE本体と統一してください

### ISSUE THREAD

**Issue by ryo-endo** [eccubevn/Recommend-plugin#5]
CSSを適用して色を青く変えていますが、
EC-CUBE本体とスタイルを統一したいので、スタイルをはずして下さい。

![image](https://cloud.githubusercontent.com/assets/16891862/19432268/d9af6238-9496-11e6-9b78-40c384a42c97.png)

**Comment by lqdung-lockon** [comment]
I've fixed it.
