### ISSUE TITLE
商品重複時のメッセージのスタイル変更

### ISSUE THREAD

**Issue by ryo-endo** [eccubevn/Recommend-plugin#6]
商品重複時のメッセージのスタイルですが、
独自のCSSでは無くdashboard.cssにある「text-info」を使用してください。

![image](https://cloud.githubusercontent.com/assets/16891862/19432560/119d3e44-9498-11e6-9dde-f69aab33a0a0.png)

**Comment by lqdung-lockon** [comment]
I've fixed it.
