### ISSUE TITLE
ドラッグ＆ドロップ中にレイアウトが崩れる

### ISSUE THREAD

**Issue by ryo-endo** [eccubevn/Recommend-plugin#8]
画像のように、ドラッグ＆ドロップ中にレイアウトが崩れます。
仕方ないようなら修正不要だと考えています。
![image](https://cloud.githubusercontent.com/assets/16891862/19433711/c5163986-949c-11e6-8c83-1c6a6ff41023.png)

**Comment by lqdung-lockon** [comment]
I've fixed it.
